# Generated by Django 3.1 on 2021-08-22 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegote', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='id_categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='juegote.categoria'),
            preserve_default=False,
        ),
    ]
